apiVersion: v1
kind: Pod 
metadata:
  name: temp 
  namespace: prat 
  labels:
    app: temp
spec: 
  containers: 
  - name: tempmed 
    image: pratikborge/nginx:latest 
    ports: 
    - containerPort: 80
      protocol: TCP 
--- 
apiVersion: v1
kind: Service 
metadata: 
  name: mytempserv 
  namespace: prat 
spec: 
  selector: 
   app: temp 
  type: NodePort 
  ports: 
   - port: 80 
     targetPort: 80 
     protocol: TCP 
     nodePort: 30080
     name: tempmed
...