apiVersion: v1
kind: Pod 
metadata:
  name: nginxtomcrate
  labels:
    app: my-app
  namespace: prat 
spec:
  containers: 
   - name: nginx
     image: nginx
     ports:
     - containerPort: 80
       protocol: TCP 
   - name: tomcat
     image: tomcat:8.5
     ports:
     - containerPort: 8080
       protocol: TCP 
   - name: db 
     image: crate 
     ports:
     - containerPort: 4200
       protocol: TCP
---
apiVersion: v1
kind: Service 
metadata: 
  name: myserv
  namespace: prat
spec:
  selector:
   app: my-app 
  type: NodePort
  ports: 
   - port: 80
     targetPort: 80
     nodePort: 30080
     name: nginx
   - port: 8080
     targetPort: 8080
     nodePort: 30081
     name: tomcat
   - port: 4200
     targetPort: 4200
     nodePort: 30082
     name: db
...