apiVersion: v1
kind: Pod 
metadata: 
  name: caddy 
  namespace: prat 
  labels: 
   app: myapp
spec: 
 containers: 
  - name: cad 
    image: caddy
    ports: 
    - containerPort: 80
      protocol: TCP 
--- 
apiVersion: v1
kind: Service 
metadata:
  name: serv1 
  namespace:  prat 
spec: 
  selector: 
   app: myapp
  type: NodePort 
  ports: 
   - port: 80
     targetPort: 80
     protocol: TCP 
     nodePort: 30080
     name: cad
...