apiVersion: apps/v1 
kind: DaemonSet 
metadata: 
   name: mydaemon 
   labels:
    app: mydaemon
spec: 
    selector: 
       matchLabels: 
          app: mydaemon 
    template: 
       metadata: 
           name: mydaemon
           labels: 
              app: mydaemon
       spec: 
          containers: 
             - name:  mynginx 
               image: nginx 
               ports: 
                  - containerPort: 80 
                    protocol: TCP 
