apiVersion: v1
kind: Service 
metadata: 
   name: nodeportsrv 
   labels: 
      app : myapp 
spec: 
    selector: 
       app: depapp 
    type: NodePort 
    ports: 
       - port: 80 
         targetPort: 80 
         nodePort: 30080 
         protocol: TCP 
         name: mycontainer 