apiVersion: v1
kind: Pod 
metadata: 
  name: light 
  namespace: prat 
  labels: 
   app: myapp
spec: 
 containers: 
  - name: lstream 
    image: lightstreamer
    ports: 
    - containerPort: 80
      protocol: TCP 
--- 
apiVersion: v1
kind: Service 
metadata:
  name: mserv 
  namespace:  prat 
spec: 
  selector: 
   app: myapp
  type: NodePort 
  ports: 
   - port: 80
     targetPort: 8080
     protocol: TCP 
     nodePort: 30080
     name: lstream 
...