apiVersion: apps/v1 
kind: StatefulSet 
metadata: 
  name: db 
  labels: 
    app: dbapp 
spec: 
    replicas: 3 
    selector: 
      matchLabels: 
        app: dbapp
    template: 
      metadata: 
         name: db 
         labels: 
            app: dbapp 
      spec: 
          containers: 
              - name: db 
                image: mysql 
                ports: 
                   - containerPort: 3306 
                     protocol: TCP 
                     name: mysql 
                env: 
                   - name: MYSQL_ROOT_PASSWORD 
                     value: "1234"          